In [ ]:
# CSV File to Pandas DataFrame

import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes

diabeties = load_diabetes

# Pandas Data Frame

diabeties_df = pd.read_csv('/content/diabetes.csv')

In [ ]:
# Finding The Type Of Data

diabeties_df = pd.read_csv('/content/diabetes.csv')
type(diabeties_df)

pandas.core.frame.DataFrame

In [ ]:
diabeties_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
print(len(diabeties_df.shape))
print(diabeties_df.shape)

2
(768, 9)

Loading an Excel File From Pandas DataFrame

Function : pd.read_excel('file path')

In [ ]:
excel = pd.read_excel('/content/Excel.xls')
print(excel.head)

<bound method NDFrame.head of       Unnamed: 0 First Name   Last Name  Gender        Country  Age  \
0              1      Dulce       Abril  Female  United States   32
1              2       Mara   Hashimoto  Female  Great Britain   25
2              3     Philip        Gent    Male         France   36
3              4   Kathleen      Hanner  Female  United States   25
4              5    Nereida     Magwood  Female  United States   58
...          ...        ...         ...     ...            ...  ...
4995        4996       Roma  Lafollette  Female  United States   34
4996        4997     Felisa        Cail  Female  United States   28
4997        4998   Demetria       Abbey  Female  United States   32
4998        4999     Jeromy        Danz    Male  United States   39
4999        5000   Rasheeda      Alkire  Female  United States   29

            Date    Id
0     15/10/2017  1562
1     16/08/2016  1582
2     21/05/2015  2587
3     15/10/2017  3549
4     16/08/2016  2468
...          ...   ...
4995  15/10/2017  2654
4996  16/08/2016  6525
4997  21/05/2015  3265
4998  15/10/2017  3265
4999  16/08/2016  6125

[5000 rows x 8 columns]>

Exporting Pandas DataFrame to CSV and Excel

In [ ]:
diabeties_dr = pd.read_csv('/content/diabetes.csv')
diabeties_excel = diabeties_dr.to_excel('Diabeties.xlsx')

Creating DaatFrame With Random Values

In [ ]:
np_random = pd.DataFrame(np.random.rand(20,10))

In [ ]:
np_random.head()

,0,1,2,3,4,5,6,7,8,9
0,0.208149,0.422538,0.230853,0.647719,0.882100,0.498974,0.360648,0.513551,0.716959,0.563536
1,0.041060,0.474746,0.589976,0.383338,0.466359,0.383188,0.510077,0.084468,0.696105,0.581029
2,0.396602,0.150076,0.413316,0.722219,0.505189,0.761339,0.587203,0.500122,0.130772,0.500726
3,0.942125,0.557923,0.139846,0.352104,0.275210,0.934484,0.938871,0.726966,0.119551,0.485223
4,0.593907,0.546050,0.138091,0.222992,0.000648,0.641158,0.190490,0.190320,0.758190,0.892224

In [ ]:
np_random.shape

(20, 10)

##Inspecting a DataFrame

In [ ]:
# Print Rows And Columns

diabeties_df.shape

(768, 9)

In [ ]:
# Print First 5 Rows and Columns Of DataFrame
diabeties_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
# Print Last 5 Rows and Columns Of DataFrame

diabeties_df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
# This Function Gives All Connon Info About DataFrame Such As
# 1) Rows and Columns
# 2) Data Type of Elements

diabeties_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [ ]:
# Finding The Number Of Missing Values Inside The Dataframe
# To say , In Python , This Function used To Find None type Elements Inside a DataFrame

diabeties_df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
diabeties_df.count(1)

0      9
1      9
2      9
3      9
4      9
      ..
763    9
764    9
765    9
766    9
767    9
Length: 768, dtype: int64

In [ ]:
# Counting The values Based On labels

diabeties_df.value_counts('Outcome')

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
diabeties_df.value_counts('Age')

Age
22    72
21    63
25    48
24    46
23    38
28    35
26    33
27    32
29    29
31    24
41    22
30    21
37    19
42    18
33    17
38    16
36    16
32    16
45    15
34    14
40    13
43    13
46    13
39    12
35    10
52     8
44     8
50     8
51     8
58     7
54     6
47     6
53     5
60     5
49     5
57     5
48     5
66     4
62     4
63     4
55     4
59     3
56     3
65     3
67     3
61     2
69     2
64     1
68     1
70     1
72     1
81     1
Name: count, dtype: int64

In [ ]:
# Group The Values based On Mean

diabeties_df.groupby('Outcome').median()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,2.0,107.0,70.0,21.0,39.0,30.05,0.336,27.0
1,4.0,140.0,74.0,27.0,0.0,34.25,0.449,36.0

In [ ]:
diabeties_df.groupby('Age').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Outcome
Age,,,,,,,,
21,1.079365,108.317460,65.936508,19.349206,73.634921,27.817460,0.433825,0.079365
22,1.555556,108.208333,63.722222,20.486111,74.486111,29.509722,0.430625,0.152778
23,1.578947,111.578947,64.315789,22.368421,118.026316,31.502632,0.438579,0.184211
24,1.891304,117.891304,64.956522,25.934783,88.021739,32.569565,0.393565,0.173913
25,1.770833,110.083333,59.666667,23.958333,82.895833,31.943750,0.600500,0.291667
26,1.969697,118.212121,64.181818,23.666667,90.878788,34.915152,0.413455,0.242424
27,2.562500,115.281250,73.500000,18.375000,63.125000,31.950000,0.471750,0.250000
28,3.028571,119.914286,68.314286,23.628571,94.600000,33.642857,0.459629,0.285714
29,3.310345,127.379310,68.241379,21.000000,88.793103,33.541379,0.408897,0.448276
30,3.619048,122.285714,64.857143,18.904762,82.666667,30.033333,0.367238,0.285714
31,3.875000,126.958333,64.375000,20.000000,111.166667,34.016667,0.589583,0.541667
32,4.437500,116.312500,70.062500,18.187500,35.812500,32.318750,0.613250,0.562500
33,4.058824,122.882353,65.647059,21.705882,85.588235,32.335294,0.734176,0.588235
34,5.857143,131.857143,74.000000,18.714286,148.071429,31.164286,0.649857,0.285714
35,5.000000,121.400000,75.600000,22.600000,75.000000,33.780000,0.454000,0.500000
36,5.187500,132.437500,69.125000,19.187500,65.812500,31.718750,0.472875,0.625000
37,5.263158,130.157895,75.947368,18.315789,59.263158,32.078947,0.414632,0.315789
38,6.875000,121.125000,71.125000,19.625000,33.500000,35.568750,0.413938,0.625000
39,7.416667,126.750000,72.666667,26.083333,72.416667,31.983333,0.605917,0.250000
40,6.230769,130.923077,69.230769,24.230769,72.307692,33.538462,0.376077,0.461538
41,6.500000,129.090909,67.590909,17.409091,38.818182,35.259091,0.396273,0.590909
42,6.888889,109.555556,73.388889,19.222222,61.277778,34.983333,0.388000,0.388889
43,7.769231,133.000000,78.461538,27.846154,125.153846,36.892308,0.450846,0.846154
44,7.250000,124.375000,61.750000,4.625000,32.250000,34.162500,0.668375,0.625000
45,7.333333,131.200000,83.066667,20.600000,31.133333,34.960000,0.496467,0.533333
46,6.384615,105.923077,76.000000,24.153846,112.307692,34.523077,0.426846,0.538462
47,8.333333,137.000000,78.333333,14.500000,49.166667,34.566667,0.355333,0.666667
48,8.800000,107.600000,78.400000,23.400000,52.000000,29.980000,0.456800,0.200000
49,7.600000,153.000000,81.400000,21.600000,55.200000,32.020000,0.612000,0.600000
50,6.750000,138.250000,78.250000,16.000000,26.375000,31.225000,0.470125,0.625000
51,8.625000,147.625000,84.500000,21.875000,129.375000,33.975000,0.615250,0.625000
52,4.625000,133.000000,81.500000,13.375000,94.500000,33.475000,0.505375,0.875000
53,5.400000,158.000000,79.000000,21.200000,183.000000,30.500000,0.550600,0.800000
54,7.000000,140.333333,89.333333,8.833333,61.000000,30.800000,0.465500,0.666667
55,5.500000,140.750000,70.250000,16.250000,83.750000,27.025000,0.226500,0.250000
56,8.000000,98.333333,76.333333,32.333333,69.000000,31.700000,0.936667,0.666667
57,8.800000,137.800000,76.800000,9.600000,78.000000,29.700000,0.704000,0.200000
58,7.142857,135.142857,78.285714,19.285714,167.857143,32.428571,0.554714,0.428571
59,2.333333,173.333333,74.000000,16.666667,282.000000,26.966667,0.252667,0.666667
60,6.000000,146.400000,80.000000,20.000000,164.200000,28.740000,0.436800,0.400000
61,5.500000,144.000000,76.000000,16.500000,95.000000,30.000000,0.613000,0.500000
62,3.750000,139.500000,71.500000,29.000000,0.000000,28.950000,0.565500,0.500000
63,5.500000,133.250000,78.000000,23.500000,45.000000,30.775000,0.249250,0.000000
64,8.000000,120.000000,78.000000,0.000000,0.000000,25.000000,0.409000,0.000000
65,3.333333,137.000000,78.666667,12.333333,0.000000,31.600000,0.259000,0.000000
66,5.000000,157.000000,86.000000,0.000000,0.000000,30.375000,0.408500,0.500000
67,4.000000,132.333333,72.666667,0.000000,0.000000,28.766667,0.602000,0.333333
68,8.000000,91.000000,82.000000,0.000000,0.000000,35.600000,0.587000,0.000000
69,5.000000,134.000000,81.000000,0.000000,0.000000,13.400000,0.413000,0.000000
70,4.000000,145.000000,82.000000,18.000000,0.000000,32.500000,0.235000,1.000000
72,2.000000,119.000000,0.000000,0.000000,0.000000,19.600000,0.832000,0.000000
81,9.000000,134.000000,74.000000,33.000000,60.000000,25.900000,0.460000,0.000000

Statistical Measure

In [ ]:
# Count Number Of Values
import pandas as pd

diabeties_df = pd.read_csv('/content/diabetes.csv')
diabeties_df.count()

Pregnancies                 768
Glucose                     768
BloodPressure               768
SkinThickness               768
Insulin                     768
BMI                         768
DiabetesPedigreeFunction    768
Age                         768
Outcome                     768
dtype: int64

In [ ]:
# Mean Value - Column Wise

diabeties_df.mean()

Pregnancies                   3.845052
Glucose                     120.894531
BloodPressure                69.105469
SkinThickness                20.536458
Insulin                      79.799479
BMI                          31.992578
DiabetesPedigreeFunction      0.471876
Age                          33.240885
Outcome                       0.348958
dtype: float64

In [ ]:
# Median - Column Wise
diabeties_df.median()

Pregnancies                   3.0000
Glucose                     117.0000
BloodPressure                72.0000
SkinThickness                23.0000
Insulin                      30.5000
BMI                          32.0000
DiabetesPedigreeFunction      0.3725
Age                          29.0000
Outcome                       0.0000
dtype: float64

In [ ]:
# Standarad Deviaton - Column Wise

diabeties_df.std()

Pregnancies                   3.369578
Glucose                      31.972618
BloodPressure                19.355807
SkinThickness                15.952218
Insulin                     115.244002
BMI                           7.884160
DiabetesPedigreeFunction      0.331329
Age                          11.760232
Outcome                       0.476951
dtype: float64

In [ ]:
# Minimum Value

diabeties_df.min()

Pregnancies                  0.000
Glucose                      0.000
BloodPressure                0.000
SkinThickness                0.000
Insulin                      0.000
BMI                          0.000
DiabetesPedigreeFunction     0.078
Age                         21.000
Outcome                      0.000
dtype: float64

In [ ]:
# Maximum Value

diabeties_df.max()

Pregnancies                  17.00
Glucose                     199.00
BloodPressure               122.00
SkinThickness                99.00
Insulin                     846.00
BMI                          67.10
DiabetesPedigreeFunction      2.42
Age                          81.00
Outcome                       1.00
dtype: float64

In [ ]:
# All the Statistical Measure

diabeties_df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

###Manipulating a DataFrame

In [5]:
# Adding a Column To a DataFrame
# target function is used

In [7]:
# Remove a Row
# Syntax : filename.drop(index,axis)

import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes

diabeties = load_diabetes

# Pandas Data Frame

diabeties_df = pd.read_csv('/content/diabetes.csv')

diabeties_df.drop(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [15]:
# Remove a Column
# Syntax : filename.drop(column='Column name')
diabeties_df2 = diabeties_df.drop(columns='Pregnancies')
diabeties_df.drop(columns='Pregnancies')

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,148,72,35,0,33.6,0.627,50,1
1,85,66,29,0,26.6,0.351,31,0
2,183,64,0,0,23.3,0.672,32,1
3,89,66,23,94,28.1,0.167,21,0
4,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...
763,101,76,48,180,32.9,0.171,63,0
764,122,70,27,0,36.8,0.340,27,0
765,121,72,23,112,26.2,0.245,30,0
766,126,60,0,0,30.1,0.349,47,1
767,93,70,31,0,30.4,0.315,23,0

In [13]:
# Locate a Partiular column

diabeties_df.iloc[2]

Pregnancies                   8.000
Glucose                     183.000
BloodPressure                64.000
SkinThickness                 0.000
Insulin                       0.000
BMI                          23.300
DiabetesPedigreeFunction      0.672
Age                          32.000
Outcome                       1.000
Name: 2, dtype: float64

In [19]:
# Locating Specific Columns

diabeties_df.iloc[:0] # Top Column
print(diabeties_df.iloc[:,0])
print(diabeties_df.iloc[:,1])
print(diabeties_df.iloc[:,2])
print(diabeties_df.iloc[:,3])

0       6
1       1
2       8
3       1
4       0
       ..
763    10
764     2
765     5
766     1
767     1
Name: Pregnancies, Length: 768, dtype: int64
0      148
1       85
2      183
3       89
4      137
      ...
763    101
764    122
765    121
766    126
767     93
Name: Glucose, Length: 768, dtype: int64
0      72
1      66
2      64
3      66
4      40
       ..
763    76
764    70
765    72
766    60
767    70
Name: BloodPressure, Length: 768, dtype: int64
0      35
1      29
2       0
3      23
4      35
       ..
763    48
764    27
765    23
766     0
767    31
Name: SkinThickness, Length: 768, dtype: int64

##Corealtion

1) Postive Coreation
2) Negative Corelated

Explanation

Take Any 2 Columns (In Diabeties DataFrame , We csn take B.P and Skin Thickness)
Let Both Be xand y

if x ∝ y, It Is Positively Corelated
if x ∝ 1/y , It is Negatively Corelated

In [20]:
diabeties_df.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
Glucose,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
BloodPressure,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
SkinThickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
Insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
BMI,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
DiabetesPedigreeFunction,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
Age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
Outcome,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000